### ISSUE TITLE
[Feat] 結果の表示とゲームリセットの処理

### ISSUE THREAD

**Issue by hanna587** [red-team-recursion/tic-tac-toe#4]
### 概要
- 結果の表示処理
- ゲームリセット（初期化）の処理を実装

### 内容の詳細
- Win or Draw の結果を表示
- ボタンクリックで、ゲーム初期化

### チェックリスト
- [x] お見本のように、画面いっぱいにだして、Resetボタンを設置
~~- [ ] 結果の表示時に、何かを降らせる~~
 
### 関連リンク
- [tictactoe Recursionお見本](https://tictactoe-tkwonn.vercel.app/)
- [落ち葉を降らせる](https://q-az.net/javascript-hirahira-ochiba/)

### そのほか
- 特記事項

***
  
🔔 Note:
- 対応時は　`$ git pull origin develop` で最新の情報を取得してください
- `$ git switch -c "新規ブランチ名" `でブランチを作成し、その中で更新してください
- 対応内容が終わったらPullRequestをたててください
- 迷ったらDiscordで相談しましょう！

**Comment by hanna587** [comment]
@Ko-nifuramu 
お疲れさまです、個人のgit拝見しました！ありがとうございます！
本当はPullRequestにかければよかったのですが、今回はIssueに失礼します。

・黒×オレンジの色合いがいいなと思いました。ゲーム画面もはっきりした黒に変更します。
・ボタンの内側に空白がほしいなと思いました。が、これはあえてなのでしょうか..？
・ねこフラシしてみました。.showのremoveでできました！（もしご対応済みでしたら、ご放念ください）
　前回どのような実装だったか失念してしまいましたが、ふらせることはできそうです（ねこじゃないほうがいいきがしてきました笑）

ひとまずコメントさせていただきました。引き続きよろしくおねがいします。

**Comment by Ko-nifuramu** [comment]
@mnyak さん
お疲れ様です。お忙しい中、gi拝見ありがとうございます！

コメントについて、
・黒×オレンジの色合いがいいなと思いました。ゲーム画面もはっきりした黒に変更します。
↓
バックグランドが黒で、文字がオレンジということでしょうか？それとも今のままってところでしょうか？

・ボタンの内側に空白がほしいなと思いました。が、これはあえてなのでしょうか..？
↓
確かに言われてみれば空白多少いれたほうがいいと思いました。ありがとうございます。空白があまりなかったのは実装時の自分が何も違和感を感じなかったからです。僕のセンスの問題でした。(T ^ T)

・ねこフラシしてみました。.showのremoveでできました！
↓
めちゃくちゃありがたいです！降らせ機能は最後に回してcpuについて実装していました。お忙しい中、僕の分もサポートしてくださってありがとうございます

アドバイスやサポート非常にありがたいです。引き続き実装の方を頑張っていこうと思います！

**Comment by hanna587** [comment]
@Ko-nifuramu にふらむさん、ありがとうございます！

> バックグランドが黒で、文字がオレンジということでしょうか？それとも今のままってところでしょうか？

失礼しました、今のままです！
黒オレンジがはっきりされてるので、ゲーム画面の線など、グレーではなく黒くはっきりさせようと思いました。

フラシ機能はどこかのタイミングで実装しますね。

センス抜群✨なのでこれからもどんどんだしていただけるとありがたいです！
こちらこそご多忙の中、諸々ありがとうございます。
気になることはご意見ください。引き続きよろしくお願いいたします。

**Comment by hanna587** [comment]
大変ありがとうございました！
